#!/bin/bash
#
# this file is part of build system for Clarity GTK+ Icons
#
# Copyright (c) 2010-2025 Jakub T. Jankiewicz <https://jcubic.pl/me>
# Licensed under CC-BY-SA 4.0 license
#

if [ "$#" -eq 2 ]; then

    SHAPE=`grep "path.*d=" $2 | sed -e "s/.*d=\"\([^\"]*\)\".*/\1/";`;\
    TITLE=`grep "<title>" $2 | sed -e "s/.*<title>\([^<]*\)<\/title>/\1/"`;\
    sed -e "s/{{PATH}}/${SHAPE}/" -e "s/{{TITLE}}/${TITLE}/" src/template_$1.svg > `echo $2 | sed -e "s/src/scalable/"`
else
    echo -e "usage:\n\tbuild <template name> src/dir/filename.svg"
fi
