#!/bin/bash

find scalable -type l | while read file; do
    path=$(echo $file | sed -e 's/[^\/]*$//');
    name=$(basename $file); desc=$(file $file | sed -e 's/.*symbolic link to \(.*\)$/\1/');
    echo "$desc $file"
done
