annotations:
  shipitcli.com/config:
    commands: {}
    php_version: 8.3.29
    phpix: true
    phpix_worker_threads: 4
    port: 8080
    use_composer: true
  shipitcli.com/provider: php
  shipitcli.com/version: 0.21.2
kind: wasmer.io/App.v0
name: clarity-icons
owner: jcubic
package: .
scaling:
  mode: single_concurrency
