CREATE TABLE IF NOT EXISTS counters (
    name VARCHAR(64) PRIMARY KEY,
    value BIGINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO counters (name, value) VALUES ('installs', 0);
